### PR TITLE
Create index.d.ts

### LINKED ISSUE #23: feat: add types for typescript
Hey there, thank you for the library! Any chance for typing to be added?

### PR DESCRIPTION
**Pull request by Eulentier161**
typescript definitions
resolves #23, closes #20

### CODE REVIEW

**Comment by mshavliuk** [comment]
Hey @anomal, why this is not getting merged?

**Comment by anomal** [comment]
Thanks for the ping. I was flooded with GitHub notifications for another project and missed this.

**Comment by dargmuesli** [comment]
Would be nice to have a new release containing that fix. It's been 6 years since the last! 🤪

**Comment by dargmuesli** [comment]
Thank you, @anomal!

**Comment by dargmuesli** [comment]
Will that version also land on https://www.npmjs.com/package/rainbowvis.js?

**Pull request merged**
